"use client";
import {useState} from "react";
import {Bell,CalendarDays,Check,ChevronRight,CircleStop,Download,FileText,Gauge,Inbox,Link2,Mail,MapPin,Pause,Play,Save,Search,Settings2,ShieldCheck,Sparkles,Upload,UserRound} from "lucide-react";
type View="profile"|"search"|"inbox"|"tracker";
const jobs=[
 {company:"Abbott",role:"Business Systems Analyst",location:"Chicago, IL",posted:"6h ago",source:"Career portal",match:92,chance:"High",status:"Applied",date:"Today, 9:18 AM",resume:"IT & Analytics · v14",proof:"Confirmation saved"},
 {company:"Northern Trust",role:"Finance Data Analyst",location:"Chicago, IL",posted:"9h ago",source:"LinkedIn → company",match:89,chance:"High",status:"Confirmation",date:"Today, 8:54 AM",resume:"Finance · v09",proof:"Email matched"},
 {company:"Zebra Technologies",role:"Software QA Analyst",location:"Lincolnshire, IL",posted:"12h ago",source:"Google Jobs",match:87,chance:"Good",status:"Needs action",date:"Today, 8:31 AM",resume:"IT & Analytics · v12",proof:"Assessment pending"},
 {company:"Rock Valley College",role:"Data Analyst",location:"Rockford, IL",posted:"18h ago",source:"University portal",match:84,chance:"Good",status:"Discovered",date:"Today, 8:06 AM",resume:"IT & Analytics · draft",proof:"Official page verified"},
];
const roles=["Business Analyst","Data Analyst","AI QA / Testing","QA / Software Testing","Banking Operations","Financial Analyst","Software Engineer"];
export default function Home(){
 const [view,setView]=useState<View>("search"),[running,setRunning]=useState(false),[link,setLink]=useState(""),[queued,setQueued]=useState(false);
 const [tasks,setTasks]=useState([{id:1,title:"Complete skills assessment",company:"Zebra Technologies",kind:"Assessment"},{id:2,title:"Approve professional reference",company:"Abbott",kind:"Reference"}]);
 const title={profile:"Profile & resumes",search:"Job search",inbox:"Action inbox",tracker:"Application tracker"}[view];
 function exportCsv(){const rows=[["Company","Role","Location","Posted","Source","Match","Chance","Status","Resume","Proof","Activity"],...jobs.map(j=>[j.company,j.role,j.location,j.posted,j.source,`${j.match}%`,j.chance,j.status,j.resume,j.proof,j.date])];const blob=new Blob([rows.map(r=>r.map(v=>`"${v}"`).join(",")).join("\n")],{type:"text/csv"});const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="babblu-applications.csv";a.click();URL.revokeObjectURL(u)}
 return <main className="shell"><aside className="sidebar"><button className="brand" onClick={()=>setView("search")}><img src="/babblu-logo.png" alt="Babblu dog logo"/><span>Babblu</span></button><nav>
  <Nav icon={<UserRound/>} label="Profile" active={view==="profile"} click={()=>setView("profile")}/><Nav icon={<Search/>} label="Search & apply" active={view==="search"} click={()=>setView("search")}/><Nav icon={<Inbox/>} label="Inbox" badge={tasks.length} active={view==="inbox"} click={()=>setView("inbox")}/><Nav icon={<Gauge/>} label="Tracker" active={view==="tracker"} click={()=>setView("tracker")}/>
 </nav><div className="trust"><ShieldCheck/><div><b>Private workspace</b><span>Proof retained</span></div></div><div className="user"><div className="avatar">AS</div><div><b>Ananya</b><span>Loves Park, IL</span></div><ChevronRight/></div></aside>
 <section className="workspace"><header className="topbar"><div><p>PERSONAL JOB PILOT</p><h1>{title}</h1></div><div><button className="icon"><Bell/></button><button className={`engine ${running?"on":""}`} onClick={()=>setRunning(!running)}>{running?<><CircleStop/>Stop engine</>:<><Play/>Start engine</>}</button></div></header>
 <div className="preview"><Sparkles/><div><b>Babblu setup mode</b><span>The workspace is interactive. Connect email, storage and supported job sources before real applications begin.</span></div></div>
 {view==="search"&&<SearchView running={running} toggle={()=>setRunning(!running)} link={link} setLink={setLink} queued={queued} queue={()=>{if(link){setQueued(true);setLink("")}}}/>} 
 {view==="profile"&&<Profile/>}{view==="inbox"&&<InboxView tasks={tasks} done={id=>setTasks(tasks.filter(t=>t.id!==id))}/>} {view==="tracker"&&<Tracker exportCsv={exportCsv}/>}</section></main>
}
function Nav({icon,label,badge,active,click}:{icon:React.ReactNode,label:string,badge?:number,active:boolean,click:()=>void}){return <button className={`nav ${active?"active":""}`} onClick={click}>{icon}<span>{label}</span>{badge?<b>{badge}</b>:null}</button>}
function SearchView({running,toggle,link,setLink,queued,queue}:{running:boolean,toggle:()=>void,link:string,setLink:(s:string)=>void,queued:boolean,queue:()=>void}){return <div className="content"><section className="hero"><div><span className={`dot ${running?"running":""}`}/>{running?"ENGINE RUNNING":"ENGINE READY"}<h2>Find early. Tailor truthfully.<br/>Apply with proof.</h2><p>Babblu prioritizes fresh, relevant openings while keeping every resume version and submission visible.</p><div className="actions"><button className="primary" onClick={toggle}>{running?<><Pause/>Pause search</>:<><Play/>Start continuous search</>}</button><button className="secondary"><Settings2/>Edit filters</button></div></div><div className="speed"><span>FRESHNESS TARGET</span><strong>&lt; 24 hours</strong><p>Newest suitable roles enter the queue first.</p><hr/><Mini k="Current mode" v={running?"Applying":"Stopped"}/><Mini k="Salary rule" v="$90K+ preferred"/><small>Lower compensation remains eligible.</small></div></section>
 <div className="metrics"><Metric n="126" label="Jobs found" note="+18 today"/><Metric n="48" label="Applied" note="+7 today"/><Metric n="2" label="Needs action" note="Inbox"/><Metric n="3" label="Interviews" note="This month"/></div>
 <section className="card"><Title over="JOB SEARCH FILTERS" title="What Babblu should look for"/><div className="controlgrid"><Select label="Role category" options={["All target roles",...roles]}/><Select label="Location" options={["Anywhere in the United States","Within 75 miles of Loves Park","Illinois only","Remote only"]}/><Select label="Work type" options={["Remote, hybrid and onsite","Remote","Hybrid","Onsite"]}/><Select label="Employment" options={["Full-time, CTH and fixed-term","Full-time only","Contract-to-hire","Fixed-term"]}/><Select label="Recently posted" options={["Past 24 hours first","Past 3 days","Past 7 days"]}/><Select label="Experience" options={["Entry level to 4 years","Entry level","1–2 years","3–4 years"]}/><Select label="Compensation" options={["$90K–$140K preferred · allow lower","$90K+ only","Any published salary"]}/><Select label="Work authorization" options={["Authorized · no sponsorship","Show all"]}/><Select label="Company type" options={["Direct employers + verified hiring partners","Direct employers only","Include startups and small employers"]}/><Select label="Application route" options={["Official portal preferred","Easy Apply allowed","All supported routes"]}/></div><div className="filterfooter"><span><ShieldCheck/> Hard disqualifiers are skipped. Salary below $90K remains eligible.</span><button className="primary"><Save/>Save filters</button></div></section>
 <section className="card"><div className="title"><div><p>SOURCE COVERAGE</p><h3>Discover broadly, verify officially</h3></div><span className="sourcecount">10 source groups</span></div><div className="sources wide">{["LinkedIn","Indeed","Handshake","Glassdoor","Jobright","Google Jobs","Company portals","Local employers","Startups","Universities"].map((s,i)=><div key={s}><i>{s[0]}</i><span>{s}</span><b>{i<7?"Ready":"Planned"}</b></div>)}</div></section>
 <section className="card paste"><div><Link2/><div><h3>Found a role elsewhere?</h3><p>Paste its URL for the priority queue.</p></div></div><div className="pastebox"><input value={link} onChange={e=>setLink(e.target.value)} placeholder="https://company.com/careers/job..."/><button onClick={queue}>Review & queue</button></div>{queued&&<p className="success"><Check/> Link queued for validation and tailoring.</p>}</section><section className="card"><Title over="RECENT ACTIVITY" title="Transparent application trail"/><JobTable/></section></div>}
function Profile(){return <div className="content"><section className="profiletop"><div><span>MY PROFILE</span><h2>Keep only the information applications need.</h2><p>These saved answers become the source of truth for every application.</p></div><button className="primary"><Save/>Save profile</button></section><section className="card"><div className="formgrid"><Field label="Full name" value="Ananya Sureshbabu"/><Field label="Current location" value="Loves Park, Illinois"/><Field label="Phone" value="(940) 597-0649"/><Field label="Email" value="ananya.s0210@gmail.com"/><Field label="Work authorization" value="Authorized now · no sponsorship required"/><Field label="Available to start" value="Immediately"/><Field label="Relocation" value="Yes · anywhere in the United States"/><Field label="Salary preference" value="$90K–$140K preferred · flexible"/></div><div className="linksrow"><Field label="LinkedIn" value="linkedin.com/in/ananya-sureshbabu-09a057206"/><Field label="GitHub" value="github.com/ananyas0210-code"/><Field label="Portfolio" value="ananya-portfolio-h76j.vercel.app"/></div></section><section className="card"><Title over="MASTER RESUMES" title="Choose from two verified starting points"/><div className="resumes"><Resume title="IT & Analytics master" tags="BA · Data · QA · AI Testing"/><Resume title="Finance master" tags="Finance · Banking Operations"/><div className="upload"><Upload/><b>Upload or replace</b><span>PDF or DOCX · 10 MB max</span></div></div><p className="integrity"><ShieldCheck/> Tailoring may reword or reorder supported facts only. Babblu never invents experience, dates, skills or results.</p></section><section className="card"><Title over="CONNECTIONS" title="Email, calendar and application updates"/><div className="connectgrid"><Connection icon={<Mail/>} title="Gmail" text="Detect confirmations, interviews and rejections"/><Connection icon={<CalendarDays/>} title="Google Calendar" text="Interview reminders and scheduling"/><Connection icon={<Link2/>} title="Job accounts" text="Connect each supported portal securely"/></div><div className="setupsteps"><b>To receive application emails:</b><span>1. Connect Gmail</span><span>2. Allow read-only job-status access</span><span>3. Choose the mailbox labels Babblu may monitor</span><span>4. Send a test notification</span></div></section></div>}
function InboxView({tasks,done}:{tasks:{id:number,title:string,company:string,kind:string}[],done:(id:number)=>void}){return <div className="content"><div className="intro"><div><h2>Only the decisions that need you.</h2><p>Other eligible applications continue while these items wait.</p></div><span>{tasks.length} open tasks</span></div>{tasks.length?<div className="tasklist">{tasks.map(t=><article className="task" key={t.id}><div className="taskicon"><FileText/></div><div><span>{t.kind}</span><h3>{t.title}</h3><p>{t.company} · Waiting for you</p></div><button className="secondary" onClick={()=>done(t.id)}>Mark complete</button><button className="primary">Open task</button></article>)}</div>:<section className="empty"><Check/><h3>You’re all clear</h3><p>Assessments, CAPTCHAs, sensitive questions and priority-company references appear here.</p></section>}</div>}
function Tracker({exportCsv}:{exportCsv:()=>void}){return <div className="content"><section className="trackerhead"><div><span>COMPLETE APPLICATION HISTORY</span><h2>Nothing is hidden.</h2><p>See where every job came from, what Babblu submitted and what happened next.</p></div><button className="primary" onClick={exportCsv}><Download/>Download CSV</button></section><div className="metrics six"><Metric n="126" label="Found" note="Past 30 days"/><Metric n="48" label="Applied" note="38% of found"/><Metric n="2" label="Pending" note="Manual action"/><Metric n="3" label="Interviews" note="6.3% response"/><Metric n="14" label="Rejected" note="Status updated"/><Metric n="0" label="Offers" note="Keep going"/></div><section className="card"><div className="title"><div><p>APPLICATION LEDGER</p><h3>Source, resume, chance, status and proof</h3></div><div className="tablefilters"><button>All statuses</button><button>Newest first</button></div></div><JobTable detailed/></section><p className="integrity"><ShieldCheck/> Each real submission should store the portal URL, confirmation email, submitted resume, timestamp and answer history for one year.</p></div>}
function Title({over,title}:{over:string,title:string}){return <div className="title"><div><p>{over}</p><h3>{title}</h3></div></div>};function Metric({n,label,note}:{n:string,label:string,note:string}){return <div className="metric"><span>{label}</span><strong>{n}</strong><small>{note}</small></div>};function Mini({k,v}:{k:string,v:string}){return <div className="mini"><span>{k}</span><b>{v}</b></div>};function Select({label,options}:{label:string,options:string[]}){return <label className="control"><span>{label}</span><select>{options.map(o=><option key={o}>{o}</option>)}</select></label>};function Field({label,value}:{label:string,value:string}){return <label className="field"><span>{label}</span><input defaultValue={value}/></label>};function Connection({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="connect"><i>{icon}</i><div><b>{title}</b><span>{text}</span></div><button>Connect</button></div>};function Resume({title,tags}:{title:string,tags:string}){return <div className="resume"><i>PDF</i><div><b>{title}</b><span>{tags}</span><small>Verified master · 2 pages</small></div><button>Replace</button></div>};function JobTable({detailed=false}:{detailed?:boolean}){return <div className="tablewrap"><table><thead><tr><th>Company & role</th>{detailed&&<th>Location / posted</th>}<th>Source</th><th>Chance</th><th>Status</th>{detailed&&<th>Resume used</th>}{detailed&&<th>Proof</th>}<th>Activity</th></tr></thead><tbody>{jobs.map(j=><tr key={j.company}><td><b>{j.company}</b><span>{j.role}</span></td>{detailed&&<td><b>{j.location}</b><span>{j.posted}</span></td>}<td>{j.source}</td><td><i className="match">{j.chance} · {j.match}%</i></td><td><i className="status">{j.status}</i></td>{detailed&&<td>{j.resume}</td>}{detailed&&<td>{j.proof}</td>}<td>{j.date}</td></tr>)}</tbody></table></div>}
